
-- mis tablas

CREATE TABLE Roles_usuario (
    id_rol_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    descripcion VARCHAR(150) NOT NULL,
    estado_registro NUMBER(1) NOT NULL,
    fecha_creacion_registro DATE NOT NULL,
    fecha_modificacion_registro DATE NOT NULL,

    CONSTRAINT PK_llave_rol_usuario PRIMARY KEY (id_rol_usuario),
    CONSTRAINT UQ_nombre_rol_unico UNIQUE (nombre)
) TABLESPACE Dev_convocatorias;

CREATE TABLE Usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    id_rol NUMBER NOT NULL,
    nombre VARCHAR(20) NOT NULL,
    apellido_paterno VARCHAR(20) NOT NULL,
    apellido_materno VARCHAR(20) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    usu VARCHAR(50) NOT NULL,
    pass VARCHAR(250) NOT NULL,
    estado_registro NUMBER(1) NOT NULL,
    fecha_creacion_registro DATE NOT NULL,
    fecha_modificacion_registro DATE NOT NULL,

    CONSTRAINT PK_llave_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT FK_referencia_rol_en_usuario FOREIGN KEY (id_rol) REFERENCES Roles_usuario(id_rol_usuario),
    CONSTRAINT UQ_usu_unico UNIQUE (usu)
) TABLESPACE Dev_convocatorias;

CREATE TABLE Tipos_documento (
    id_tipo_documento NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    descripcion VARCHAR(150) NOT NULL,
    estado_registro NUMBER(1) NOT NULL,
    fecha_creacion_registro DATE NOT NULL,
    fecha_modificacion_registro DATE NOT NULL,

    CONSTRAINT PK_llave_tipo_documento PRIMARY KEY (id_tipo_documento),
    CONSTRAINT UQ_nombre_tipo_documento_unico UNIQUE (nombre)
) TABLESPACE Dev_convocatorias;

CREATE TABLE Documentos (
    id_documento NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    id_tipo NUMBER NOT NULL,
    id_usuario NUMBER NOT NULL,
    ruta VARCHAR(250) NOT NULL,
    estado_registro NUMBER(1) NOT NULL,
    fecha_creacion_registro DATE NOT NULL,
    fecha_modificacion_registro DATE NOT NULL,

    CONSTRAINT PK_llave_documentos PRIMARY KEY (id_documento),
    CONSTRAINT FK_referencia_tipo_documentos FOREIGN KEY (id_tipo) REFERENCES Tipos_documento(id_tipo_documento),
    CONSTRAINT FK_referencia_usuario_documentos FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario)
) TABLESPACE Dev_convocatorias;

CREATE TABLE Empresas (
    id_empresa NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    id_usuario NUMBER NOT NULL,
    nombre_comercial VARCHAR(150) NOT NULL,
    razon_social VARCHAR(150) NOT NULL,
    fecha_fundacion DATE NOT NULL,
    estado_registro NUMBER(1) NOT NULL,
    fecha_creacion_registro DATE NOT NULL,
    fecha_modificacion_registro DATE NOT NULL,

    CONSTRAINT PK_llave_empresas PRIMARY KEY (id_empresa),
    CONSTRAINT FK_referencia_usuario_empresas FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario),
    CONSTRAINT UQ_usuario_unico_empresa UNIQUE (id_usuario),
    CONSTRAINT UQ_nombre_comercial_unico UNIQUE (nombre_comercial),
    CONSTRAINT UQ_razon_social_unico UNIQUE (razon_social)
) TABLESPACE Dev_convocatorias;

CREATE TABLE Tipos_jornada (
    id_jornada NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(250) NOT NULL,
    estado_registro NUMBER(1) NOT NULL,
    fecha_creacion_registro DATE NOT NULL,
    fecha_modificacion_registro DATE NOT NULL,

    CONSTRAINT PK_llave_tipos_jornada PRIMARY KEY (id_jornada),
    CONSTRAINT UQ_nombre_tipo_jornada_unico UNIQUE (nombre)
) TABLESPACE Dev_convocatorias;

CREATE TABLE Tipos_modalidad (
    id_tipo_modalidad NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(250) NOT NULL,
    estado_registro NUMBER(1) NOT NULL,
    fecha_creacion_registro DATE NOT NULL,
    fecha_modificion_registro DATE NOT NULL,

    CONSTRAINT PK_llave_tipos_modalidad PRIMARY KEY (id_tipo_modalidad),
    CONSTRAINT UQ_nombre_tipo_modalidad_unico UNIQUE (nombre)
) TABLESPACE Dev_convocatorias;

CREATE TABLE Convocatorias (
    id_convocatoria NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    id_tipo_jornada NUMBER NOT NULL,
    id_tipo_modalidad NUMBER NOT NULL,
    id_empresa NUMBER NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    descripcion VARCHAR(500) NOT NULL,
    estado_registro NUMBER(1) NOT NULL,
    fecha_creacion_registro DATE NOT NULL,
    fecha_modificacion_registro DATE NOT NULL,

    CONSTRAINT PK_llave_convocatorias PRIMARY KEY (id_convocatoria),
    CONSTRAINT FK_referencia_empresa_convocatorias FOREIGN KEY (id_empresa) REFERENCES Empresas (id_empresa),
    CONSTRAINT FK_referencia_jornada_convocatorias FOREIGN KEY (id_tipo_jornada) REFERENCES Tipos_jornada (id_jornada),
    CONSTRAINT FK_referencia_modalidad_convocatorias FOREIGN KEY (id_tipo_modalidad) REFERENCES Tipos_modalidad (id_tipo_modalidad),
    CONSTRAINT UQ_titulo_unico_convocatorias UNIQUE (titulo)
) TABLESPACE Dev_convocatorias;

CREATE TABLE Estados_postulacion (
    id_estado_postulacion NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 ) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(250) NOT NULL,
    estado_registro NUMBER(1) NOT NULL,
    fecha_creacion_registro DATE NOT NULL,
    fecha_modificacion_registro DATE NOT NULL,

    CONSTRAINT PK_llave_estados_postulacion PRIMARY KEY (id_estado_postulacion),
    CONSTRAINT UQ_nombre_estados_postulacion_unicos UNIQUE (nombre)
) TABLESPACE Dev_convocatorias;

CREATE TABLE Resoluciones_postulacion (
    id_resolucion_postulacion NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(250) NOT NULL,
    estado_registro NUMBER(1) NOT NULL,
    fecha_creacion_registro DATE NOT NULL,
    fecha_modificacion_registro DATE NOT NULL,

    CONSTRAINT PK_llave_resoluciones_postulacion PRIMARY KEY (id_resolucion_postulacion),
    CONSTRAINT UQ_nombre_resolucion_unico UNIQUE (nombre)
) TABLESPACE Dev_convocatorias;

CREATE TABLE Postulaciones (
    id_postulacion NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    id_convocatoria NUMBER NOT NULL,
    id_usuario NUMBER NOT NULL,
    id_estado NUMBER NOT NULL,
    id_resolucion NUMBER NOT NULL,
    estado_registro NUMBER(1) NOT NULL,
    fecha_creacion_registro DATE NOT NULL,
    fecha_modificacion_registro DATE NOT NULL,

    CONSTRAINT PK_llave_postulaciones PRIMARY KEY (id_postulacion),
    CONSTRAINT FK_referencia_convocatorias_postulaciones FOREIGN KEY (id_convocatoria) REFERENCES Convocatorias(id_convocatoria),
    CONSTRAINT FK_referencia_usuario_postulaciones FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario),
    CONSTRAINT FK_referencia_estado_postulacioens FOREIGN KEY (id_estado) REFERENCES Estados_postulacion(id_estado_postulacion),
    CONSTRAINT FK_referencia_resolucion_postualciones FOREIGN KEY (id_resolucion) REFERENCES Resoluciones_postulacion(id_resolucion_postulacion) 
) TABLESPACE Dev_convocatorias;

-- ahora voy a establecer mis indices para una mejor busqueda de datos

CREATE INDEX IDX_codigo_jornada_convocatorias ON Convocatorias (id_tipo_jornada) TABLESPACE Dev_convocatorias;
CREATE INDEX IDX_codigo_modalidad_convocatorias ON Convocatorias (id_tipo_modalidad) TABLESPACE Dev_convocatorias;
CREATE INDEX IDX_codigo_empresa_convocatorias ON Convocatorias (id_empresa) TABLESPACE Dev_convocatorias;

CREATE INDEX IDX_codigo_tipo_documento ON Documentos (id_tipo) TABLESPACE Dev_convocatorias;
CREATE INDEX IDX_codigo_usuario_documentos ON Documentos (id_usuario) TABLESPACE Dev_convocatorias;
CREATE INDEX IDX_ruta_documento ON Documentos (ruta) TABLESPACE Dev_convocatorias;

CREATE INDEX IDX_codigo_convocatoria_portulaciones ON Postulaciones (id_convocatoria) TABLESPACE Dev_convocatorias;
CREATE INDEX IDX_codigo_usuario_postulaciones ON Postulaciones (id_usuario) TABLESPACE Dev_convocatorias;
CREATE INDEX IDX_codigo_estado_postulacion_postulaciones ON Postulaciones (id_estado) TABLESPACE Dev_convocatorias;
CREATE INDEX IDX_codigo_resolucion_postulacion ON Postulaciones (id_resolucion) TABLESPACE Dev_convocatorias;

CREATE INDEX IDX_codigo_rol_usuarios ON Usuarios (id_rol) TABLESPACE Dev_convocatorias;
CREATE INDEX IDX_nombre_usuarios ON Usuarios (nombre) TABLESPACE Dev_convocatorias;
CREATE INDEX IDX_fecha_nacimiento_usuarios ON Usuarios (fecha_nacimiento) TABLESPACE Dev_convocatorias;
