
CREATE TABLE Roles_usuario (
    id_rol_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    descripcion VARCHAR(150) NOT NULL,
    estado_registro BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion_registro DATE NOT NULL,
    fecha_modificaion_registro DATE NOT NULL,

    CONSTRAINT pk_llave_rol_usuario PRIMARY KEY (id_rol_usuario),
    CONSTRAINT uq_nombre_rol_unico UNIQUE (nombre)
);

CREATE TABLE Usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    id_rol INTEGER NOT NULL,
    nombre VARCHAR(20) NOT NULL,
    apellido_paterno VARCHAR(20) NOT NULL,
    apellido_materno VARCHAR(20) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    usu VARCHAR(50) NOT NULL,
    pass VARCHAR(250) NOT NULL,
    estado_registro BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion_registro DATE NOT NULL,
    fecha_modificacion_registro DATE NOT NULL,

    CONSTRAINT pk_llave_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT fk_referencia_rol_en_usuario FOREIGN KEY (id_rol) REFERENCES Roles_usuario(id_rol_usuario),
    CONSTRAINT uq_usu_unico UNIQUE (usu)
);

CREATE TABLE Tipos_documento (
    id_tipo_documento INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    descripcion VARCHAR(150) NOT NULL,
    estado_registro BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion_registro DATE NOT NULL,
    fecha_modificacion_registro DATE NOT NULL,

    CONSTRAINT pk_llave_tipo_documento PRIMARY KEY (id_tipo_documento),
    CONSTRAINT uq_nombre_tipo_documento_unico UNIQUE (nombre)
);

CREATE TABLE Documentos (
    id_documento INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    id_tipo INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    ruta VARCHAR(250) NOT NULL,
    estado_registro BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion_registro DATE NOT NULL,
    fecha_modificacion_registro DATE NOT NULL,

    CONSTRAINT pk_llave_documentos PRIMARY KEY (id_documento),
    CONSTRAINT fk_referencia_tipo_documentos FOREIGN KEY (id_tipo) REFERENCES Tipos_documento(id_tipo_documento),
    CONSTRAINT fk_referencia_usuario_documentos FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario)
);

CREATE TABLE Empresas (
    id_empresa INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    id_usuario INTEGER NOT NULL,
    nombre_comercial VARCHAR(150) NOT NULL,
    razon_social VARCHAR(150) NOT NULL,
    fecha_fundacion DATE NOT NULL,
    estado_registro BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion_registro DATE NOT NULL,
    fecha_modificacion_registro DATE NOT NULL,

    CONSTRAINT pk_llave_empresas PRIMARY KEY (id_empresa),
    CONSTRAINT fk_referencia_usuario_empresas FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario),
    CONSTRAINT uq_usuario_unico_empresa UNIQUE (id_usuario),
    CONSTRAINT uq_nombre_comercial_unico UNIQUE (nombre_comercial),
    CONSTRAINT uq_razon_social_unico UNIQUE (razon_social)
);

